CREATE TABLE `Usuario` (
	Id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	Username VARCHAR(30) NOT NULL,
	Password VARCHAR(255) NOT NULL
);

CREATE TABLE `Post` (
	Id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	Titulo VARCHAR(40) NOT NULL,
	UltimaActualizacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	Contenido MEDIUMTEXT,
	IdUsuario INT UNSIGNED NOT NULL,
	CONSTRAINT fk_post_usuario FOREIGN KEY (IdUsuario) REFERENCES USUARIO(Id)
);
