@simple_crud.Api_HostAddress = http://localhost:5250

GET {{simple_crud.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{simple_crud.Api_HostAddress}}/api/usuario

###

GET {{simple_crud.Api_HostAddress}}/api/usuario/1

###

POST {{simple_crud.Api_HostAddress}}/api/usuario
Content-Type: application/json
{
  "username": "AndersonSilva2",
  "password": "thisisansecretpassword"
}

###

POST {{simple_crud.Api_HostAddress}}/api/auth/login
Content-Type: application/json
{
  "username": "testuser",
  "password": "secretpassword"
}

###

POST {{simple_crud.Api_HostAddress}}/api/auth/logout

###

DELETE {{simple_crud.Api_HostAddress}}/api/usuario
Content-Type: application/json
{
  "id": "3",
  "password": "thisisansecretpassword"
}

###

PUT {{simple_crud.Api_HostAddress}}/api/usuario
Content-Type: application/json
{
  "id": "5",
  "username": "AndersonSilvaUpdated2",
  "password": "thisisansecretpassword"
}

###